encoding: utf-8
name: "DocDoku user guides"
exclude: [bower_components]
languages: ["en", "fr"]
versions: ["1.1", "1.1-RC1"]
defaultlanguage: ["en"]
relative_permalinks: true
url: /docdoku-plm/user-guide/
markdown: kramdown